### ISSUE TITLE
STR damage on attacks drives script crazy

### ISSUE THREAD

**Issue by EasternTime** [FGKenL/Roll20_API_Scripts#2]
Today I've tried to parse with CreatureGen this mob from the Tome of Horrors:

Black Skeleton CR 5
XP 1,600
CE Medium undead
Init +8; Senses darkvision 60 ft.; Perception +10
Aura frightful presence (60 ft., DC 15)
Defense
AC 20, touch 14, flat-footed 16 (+4 Dex, +6 natural)
hp 45 (7d8+14)
Fort +4; Ref +6; Will +5
Defensive Abilities channel resistance +4; DR 10/bludgeoning and good; Immune undead traits
Offense
Speed 40 ft.
Melee 2 short swords +10 (1d6/19–20 plus 1d3 Strength damage) or 2 claws +9 (1d4 plus 1d3 Strength damage)
Special attacks superior two-weapon fighting
Statistics
Str 11, Dex 19, Con —, Int 13, Wis 10, Cha 14
Base Atk +5; CMB +5; CMD 19
Feats Improved Initiative, Two-Weapon Fighting, Weapon Finesse, Weapon Focus (short sword)
Skills Acrobatics +11, Climb +10, Escape Artist +11, Perception +10, Stealth +14
Languages Abyssal, Common
Gear 2 short swords
Environment underground
Organization any
Treasure standard
Stength Damage (Su) A black skeleton’s attacks (either by a weapon or natural attack) deal 1d3 points of Strength damage to a living creature. This is a negative energy effect. This is a function of the black skeleton itself, not its weapons.
Superior Two-Weapon Fighting (Ex) A black skeleton usually fights with a short sword in each hand. Because of its magical nature, its Two-Weapon Fighting feat allows it to attack with both weapons at no penalty.

Get this error every time:
"GENESIS ERROR: ERROR: could not find attribute Dex"

After some debugging I found script tries to parse this line for attributes instead of right one:
"Melee 2 short swords +10 (1d6/19-20 plus 1d3 Strength damage) or 2 claws +9 (1d4 plus 1d3 Strength damage)"

Looks like getLineByName function acts wierd for some reason.

**Comment by RPGKenL** [comment]
I don't support roll20 scripts as I have left that platform over a year ago.

If it's of any help, I've used that creature before (it's one of the interesting early encounters in Rappan) and it parsed correctly.

From what I see, there's nothing wrong with that stat block. I hear roll20 has gone through several API backend changes so there's that. I can help you no more than that.

Cheers,
- Ken
